const aiEls={enabled:document.getElementById('enabled'),endpoint:document.getElementById('endpoint'),saveBtn:document.getElementById('saveBtn'),resetBtn:document.getElementById('resetBtn'),testBtn:document.getElementById('testBtn'),statusCard:document.getElementById('statusCard'),statusText:document.getElementById('statusText'),modelText:document.getElementById('modelText'),toast:document.getElementById('toast')};

function loadAISettings(){const settings=window.DAOSAI.loadSettings();aiEls.enabled.checked=settings.enabled;aiEls.endpoint.value=settings.endpoint;}
function toast(message){aiEls.toast.textContent=message;aiEls.toast.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>aiEls.toast.classList.remove('show'),2200)}
function renderStatus(tone,title,detail){aiEls.statusCard.className=`ai-status ${tone}`;aiEls.statusText.textContent=title;aiEls.modelText.textContent=detail;}
function saveAISettings(){window.DAOSAI.saveSettings({enabled:aiEls.enabled.checked,endpoint:aiEls.endpoint.value.trim(),healthEndpoint:aiEls.endpoint.value.trim().replace(/\/api\/reason(?:\?.*)?$/,'/api/health')});toast('AI settings saved locally.');testConnection(false);}
async function testConnection(showToast=true){renderStatus('warn','Checking…','Testing the server-side reasoning proxy.');try{const health=await window.DAOSAI.health();if(health.aiConfigured){renderStatus('good','READY',`${health.provider||'AI backend'} · ${health.model||'model configured'}`);if(showToast)toast('AI reasoning backend is ready.');}else{renderStatus('warn','SERVER UP · AI OFF','The proxy is reachable, but no server-side AI key is configured. Deterministic DA.OS still works.');if(showToast)toast('Server reachable; AI key is not configured.');}}catch(error){renderStatus('bad','UNAVAILABLE',error.message||'Could not reach the AI backend.');if(showToast)toast(error.message||'AI connection failed.');}}
function resetAISettings(){window.DAOSAI.saveSettings({enabled:false,endpoint:'/api/reason',healthEndpoint:'/api/health'});loadAISettings();renderStatus('neutral','Not checked','Deterministic DA.OS remains available.');toast('AI settings reset.');}

aiEls.saveBtn.addEventListener('click',saveAISettings);aiEls.resetBtn.addEventListener('click',resetAISettings);aiEls.testBtn.addEventListener('click',()=>testConnection(true));loadAISettings();testConnection(false);
